github action でUnit テストを回すための yaml 作成
yumemi-inc/ios-training-bjung pull request #11
Opened 2024-01-18 01:06 UTC by askldfghj

## 概要

github action でUnit テストを回すための yaml 作成

## セッションリンク

なし

## 変更点

github actions を通して、 main、session 向けに pullRequest を出した際に github actions でテストを回すようにする

## スクリーンショット

2024-01-18 01:16 UTC, askldfghj commented
ローカルではプロジェクトが見つからないというのと、マージされてないので actions タブで結果が見れない状況です。
ローカルでの確認方法は run のコマンドをそのまま試したものですが、やり方違うですかね・・

2024-01-19 13:24 UTC, novr requested changes

2024-01-19 13:24 UTC, novr commented on .github/workflows/test.yml
> +    branches: [ "main, session/*" ]
```suggestion
    branches: [ "main", "session/*" ]
```

2024-01-22 01:54 UTC, askldfghj commented on .github/workflows/test.yml
> +    branches: [ "main, session/*" ]
@novr 
コメントありがとうございます。
6ac453275927c9d31385e67fb826c4cd9b55471f
上記のコミットで修正しました。
また、iOS 15 はないと言われたので 14 に修正してプッシュしましたが、以下のように失敗になりました。
https://github.com/yumemi-inc/ios-training-bjung/actions/runs/7605165295/job/20709054621

```The test runner encountered an error (Failed to establish communication with the test runner. If you believe this error represents a bug, please attach the log file at /Users/runner/work/ios-training-bjung/ios-training-bjung/TestResults/Staging/1_Test/Diagnostics/ios-training-bjungUITests-ADC573BE-57F3-4186-B68B-6A51B97E0C62-Configuration-Test Scheme Action-Iteration-1/ios-training-bjungUITests-48B14BAC-1AAE-41F0-8FBE-244CC3744C78/Session-ios-training-bjungUITests-2024-01-22_011603-PFtPIB.log. (Underlying Error: Error retrieving daemon unix domain socket from simulator, failed after 30 attempts.; getenv error: Error Domain=com.apple.CoreSimulator.SimError Code=405 "Unable to getenv("TESTMANAGERD_SIM_SOCK") while not booting or booted.  Current state: Shutdown" UserInfo={NSLocalizedDescription=Unable to getenv("TESTMANAGERD_SIM_SOCK") while not booting or booted.  Current state: Shutdown}))```

というエラーで、json マッピングテスト以外は通っていました。
ローカルでは通っているのですが、 github action の環境と関係あるでしょうか・・・

2024-01-23 00:46 UTC, ykws commented on .github/workflows/test.yml
> +      - uses: maxim-lobanov/setup-xcode@v1
これは何のために必要でしたか？
macOS デフォルトで Xcode セットアップされているような

2024-01-23 00:46 UTC, ykws commented on .github/workflows/test.yml
> +    branches: [ "main, session/*" ]
ローカルだとパスするので、 GitHub Actions 環境の問題ですかね
すぐに原因がわからなかったです

iPhone は 14 までですね。下記が GitHub Actions で対応している Simulators です
https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#installed-simulators

2024-01-23 00:51 UTC, ykws commented on .github/workflows/test.yml
> +    branches: [ "main, session/*" ]
iOS17 なら 15 もありました

<img width="551" alt="スクリーンショット 2024-01-23 9 50 18" src="https://github.com/yumemi-inc/ios-training-bjung/assets/5770480/882fb330-b315-481c-83de-581461b5dd20">

2024-01-23 01:17 UTC, ykws commented on .github/workflows/test.yml
> +      - uses: maxim-lobanov/setup-xcode@v1
@askldfghj 削除しても変わらないですね。

ちなみに下記結果出力を追加するとどういう結果で失敗しているか見えるようになるので良かったら導入してみてください

https://github.com/kishikawakatsumi/xcresulttool

Usage に記載の通り UnitTest の後に次のステップを追加します

```yaml
- uses: kishikawakatsumi/xcresulttool@v1
  with:
    path: TestResults.xcresult
  if: success() || failure()
```

2024-01-23 01:44 UTC, novr reviewed
テストの失敗はTimeZoneの設定かな

2024-01-23 01:44 UTC, novr commented on .github/workflows/test.yml
> +        run: xcodebuild test -project ios-training-bjung.xcodeproj/ -scheme ios-training-bjung -resultBundlePath TestResults -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14"
[imo] xcbeautifyすると不要そうなログがでないのでおすすめ
```suggestion
        run: set -o pipefail && xcodebuild test -project ios-training-bjung.xcodeproj/ -scheme ios-training-bjung -resultBundlePath TestResults -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14" | xcbeautify
```

2024-01-23 01:51 UTC, askldfghj commented on .github/workflows/test.yml
> +        run: xcodebuild test -project ios-training-bjung.xcodeproj/ -scheme ios-training-bjung -resultBundlePath TestResults -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14"
xcresulttool 入れたら、確かに TimeZone の問題なのがわかりましたね。
まず xcbeautify を入れてプッシュしました。

2024-01-23 03:18 UTC, askldfghj commented on .github/workflows/test.yml
> +        run: xcodebuild test -project ios-training-bjung.xcodeproj/ -scheme ios-training-bjung -resultBundlePath TestResults -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14"
@novr 
TimeZone 指定でテストが通りました。

2024-01-23 03:19 UTC, askldfghj commented on .github/workflows/test.yml
> +      - uses: maxim-lobanov/setup-xcode@v1
@ykws 
3bb88ad64d88603f1b058dddc9a62f336aae9ea7
こちらのコミットで導入しました。

2024-01-23 03:30 UTC, novr approved these changes
現在、何もしてないUIテストは削除した方が早いかと

2024-01-23 05:03 UTC, askldfghj commented
```
Failed to establish communication with the test runner. If you believe this error represents a bug, please attach the log file at /Users/runner/work/ios-training-bjung/ios-training-bjung/TestResults/Staging/1_Test/Diagnostics/ios-training-bjungTests-FDE7F106-A595-454E-A890-51029F20B193-Configuration-Test Scheme Action-Iteration-1/ios-training-bjungTests-F909F0B9-AAE0-47DB-AB14-5D251D746C26/Session-ios-training-bjungTests-2024-01-23_044014-pSWGzN.log. (Underlying Error: Error retrieving daemon unix domain socket from simulator, failed after 30 attempts.; getenv error: Error Domain=com.apple.CoreSimulator.SimError Code=405 "Unable to getenv("TESTMANAGERD_SIM_SOCK") while not booting or booted. Current state: Shutdown" UserInfo={NSLocalizedDescription=Unable to getenv("TESTMANAGERD_SIM_SOCK") while not booting or booted. Current state: Shutdown})
```
https://github.com/yumemi-inc/ios-training-bjung/pull/11/checks?check_run_id=20757148269#user-content-ios-training-bjungtests_ios-training-bjung-encountered-an-error

何だこれ・・・

2024-01-23 14:30 UTC, ykws commented
> 現在、何もしてないUIテストは削除した方が早いかと

ios_training_bjungUITestsLaunchTests を含めて ios-training-bjungUITests のテストターゲットのことを指していたかなと思いました

削除後のエラーはちょっとわからないですね。。
一度 Rerun して再現性があるか確認してみてください

2024-01-24 01:39 UTC, askldfghj commented
@ykws 
ios-training-bjungUITests のターゲットから削除しました。
また、このプッシュに対してもテストは通りました。
時に起きる問題ですかね・・・

2024-01-25 03:54 UTC, ykws approved these changes
動いてそうですね 👍

2024-01-25 03:55 UTC, ykws commented
> 時に起きる問題ですかね・・・

わからないですね。自分は見たことがなかったと思います。再現性があるものなのか、実際に導入してみて経過観察ですかね

2024-01-30 00:45 UTC, askldfghj commented
@ykws @novr 
レビューありがとうございます。こちらマージします。

2024-01-30 01:26 UTC, merged