session 11 の課題実装
yumemi-inc/ios-training-bjung pull request #12
Opened 2024-01-22 03:40 UTC by askldfghj

## 概要

session 11 の課題を実装しました。

## セッションリンク

https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Callback.md

## 変更点

- view の更新を output の protocol ではなく、 completion パターンで更新するように修正

## スクリーンショット

![session_11](https://github.com/yumemi-inc/ios-training-bjung/assets/18435420/5f289151-61ab-4b0e-86eb-0e81eecb6a67)

2024-01-22 03:44 UTC, askldfghj commented on ios-training-bjung/Views/HomeViewController.swift
> +    private func updateDisplayScreen(response: WeatherResponse) {
private 化になり、view で直接修正するような形になりましたが、 presenter を介しての結果なので大丈夫かな、と思いました。

2024-01-22 03:44 UTC, askldfghj commented on ios-training-bjung/Views/HomeViewController.swift
> +    private func updateDisplayScreen(response: WeatherResponse) {
関数名の変更は一度関数を削除したためですが、 Info なしでもいいかなと思いました。

2024-01-23 02:50 UTC, novr commented on ios-training-bjung/Views/HomeViewController.swift
> +            self.updateDisplayScreen(response: response)
[imo] APIの結果をコールバックで受け取る事が要件です
MVP構成でViewがコールバックを渡してしまうと、ロジックを持ってしまい責務の分離が曖昧になってしまいます

2024-01-23 03:22 UTC, askldfghj commented on ios-training-bjung/Views/HomeViewController.swift
> +            self.updateDisplayScreen(response: response)
@novr 
あー。
ということは、 Presenter がコールバックを持って Model にそれを渡すのが今の設計で正しいでしょうか？

2024-01-23 05:03 UTC, askldfghj commented
```
Failed to establish communication with the test runner. If you believe this error represents a bug, please attach the log file at /Users/runner/work/ios-training-bjung/ios-training-bjung/TestResults/Staging/1_Test/Diagnostics/ios-training-bjungTests-FDE7F106-A595-454E-A890-51029F20B193-Configuration-Test Scheme Action-Iteration-1/ios-training-bjungTests-F909F0B9-AAE0-47DB-AB14-5D251D746C26/Session-ios-training-bjungTests-2024-01-23_044014-pSWGzN.log. (Underlying Error: Error retrieving daemon unix domain socket from simulator, failed after 30 attempts.; getenv error: Error Domain=com.apple.CoreSimulator.SimError Code=405 "Unable to getenv("TESTMANAGERD_SIM_SOCK") while not booting or booted. Current state: Shutdown" UserInfo={NSLocalizedDescription=Unable to getenv("TESTMANAGERD_SIM_SOCK") while not booting or booted. Current state: Shutdown})
```
https://github.com/yumemi-inc/ios-training-bjung/pull/11/checks?check_run_id=20757148269#user-content-ios-training-bjungtests_ios-training-bjung-encountered-an-error

何だこれ・・・

2024-01-23 07:41 UTC, askldfghj commented on ios-training-bjung/Views/HomeViewController.swift
> +            self.updateDisplayScreen(response: response)
@novr 
9eb54145eaa1fe056d951b73ae774cbd820d291a
367e375afd63b73409454de0892bb7fe93d58356
上記のコミットで設計とテストの修正を行いました。

2024-01-23 07:51 UTC, novr requested changes

2024-01-23 07:51 UTC, novr commented on ios-training-bjung/Models/WeatherModel.swift
> +    func fetchWeatherData(request: WeatherRequest, completion: @escaping @Sendable @MainActor (WeatherResponse) -> ()) async throws
[imo] async版はそれとして残しておいてもよいかと
[must] ModelにViewの都合である@MainActorが漏れています
また、completionがあることで非同期で実行される事が期待されるので、asyncは不要かと

2024-01-23 07:51 UTC, novr commented on ios-training-bjung/Models/WeatherModel.swift
> +        await completion(try Mapper.decodeWeatherResponse(json: response))
[imo] modelで非同期で実行されるべき(MainThreadを止めない)は外部(`yumemiWeather`)とのやりとり(IO)の部分です
Taskで切り出すと良いかと思います

2024-01-24 00:18 UTC, askldfghj commented on ios-training-bjung/Models/WeatherModel.swift
> +    func fetchWeatherData(request: WeatherRequest, completion: @escaping @Sendable @MainActor (WeatherResponse) -> ()) async throws
@novr 
コメントありがとうございます。

> [must] ModelにViewの都合である@MainActorが漏れています

Model クラス自体に漏れていると言うことでしょうか、それとも追加した関数に必要ということでしょうか。

2024-01-24 00:21 UTC, askldfghj commented on ios-training-bjung/Models/WeatherModel.swift
> +        await completion(try Mapper.decodeWeatherResponse(json: response))
@novr 

```
let jsonString = try Mapper.encodeWeatherRequest(request: request)
let response = try yumemiWeather.syncFetchWeather(jsonString)
completion(try Mapper.decodeWeatherResponse(json: response))
```

こちらを Task で切り出してみたのですが、エラー発生時の場合 Presenter の do catch でキャッチできず・・・
コールバックにする場合、 model 側でエラーハンドリングできるように、Presenter の関数を渡すのがいいでしょうか。（従属されてしまうので多分間違った解答になりそうですが）

2024-01-24 01:49 UTC, novr commented on ios-training-bjung/Models/WeatherModel.swift
> +    func fetchWeatherData(request: WeatherRequest, completion: @escaping @Sendable @MainActor (WeatherResponse) -> ()) async throws
WeatherModelInputはModelの責務なので、Model側にです

2024-01-24 01:50 UTC, novr commented on ios-training-bjung/Models/WeatherModel.swift
> +        await completion(try Mapper.decodeWeatherResponse(json: response))
Model(API)の結果をcompletionで受け取るので、Result型などで受け取ってみましょう
https://developer.apple.com/documentation/swift/result

2024-01-26 05:32 UTC, askldfghj commented on ios-training-bjung/Models/WeatherModel.swift
> +        await completion(try Mapper.decodeWeatherResponse(json: response))
@novr 
e12d45e0c794e79e5f6d2af0df1ae36cd035bab9
上記のコミットで以下の対応を行いました。
* Presenter を MainActor に修正
* Model に Presenter のコールバックを追加
* 隔離問題の解消のため、 API は inject ではなく YumemiWeather そのまま利用

2024-01-28 13:43 UTC, es-kumagai commented on ios-training-bjung/Common/AppError.swift
> +public enum AppError: LocalizedError, Sendable {
```suggestion
public enum AppError: LocalizedError {
```

LocalizedError プロトコルは、その元となる Error プロトコルが `Sendable` に準拠しているので、ここで `Sendable` は記載不要です。

![Q-badge](https://img.shields.io/badge/review-Q-plum.svg)

特に追記しなくてもコンパイルで指摘されるようなことはなかったと思うのと、自分的には書かなくて問題ないように思っているので、何か不都合で書く必要に迫られたとしたら教えてください。

2024-01-29 02:47 UTC, novr commented on ios-training-bjung/Presenters/HomePresenter.swift
>      @MainActor
[imo] outputはView(`@MainActor`)であることが明確なので `@MainActor` をclass宣言に移動してもよいかと

2024-01-29 05:22 UTC, es-kumagai commented on ios-training-bjung/Models/WeatherModel.swift
> +struct WeatherResponse: Decodable, Sendable {
![imho-badge](https://img.shields.io/badge/review-imho-tan.svg) ![fyi-badge](https://img.shields.io/badge/review-fyi-tan.svg)

public でない構造体で敢えて `Sendable` 明記することで「この構造体は、非 Sendable なメンバーを持つことができない」みたいな喚起に繋げられるので、方針によっては明記しても良いかもしれないです。

ローカルプロジェクト内なので、当該構造体に間違って非 Sendable なメンバーを含めたときに直ぐに発覚しますし、記載しないことで不都合はないと思うので、そんなあたりを考慮して、記載の有無を選択してみるのも有意義かもしれないです。

2024-01-30 00:24 UTC, askldfghj commented on ios-training-bjung/Common/AppError.swift
> +public enum AppError: LocalizedError, Sendable {
@es-kumagai 
コメントありがとうございます。
concurrency のコンパイル設定を complete にしたため、 別スレッドでのコールバックの呼び出しに Sendable としてキャプチャーしてと warning が出たため、明記したら変わるのか？と入れてみた痕跡が残っていました。
こちら不要というのは認知しているため、
b8fa170b33fd883fe64067d2a3e3419c148a8db0
上記のコミットで削除しました。

2024-01-30 00:25 UTC, askldfghj commented on ios-training-bjung/Presenters/HomePresenter.swift
>      @MainActor
@novr 
コメントありがとうございます。
c779c049c1e129c43577689665aa0bb974fdeb44
上記のコミットで対応しました。
Input に関しては MainActor のみで、 Presenter も MainActor になったのですが、 protocol としては分離させた方がいいかなと思い、そのままにしていいます。

2024-01-30 00:28 UTC, askldfghj commented on ios-training-bjung/Models/WeatherModel.swift
> +struct WeatherResponse: Decodable, Sendable {
@novr @es-kumagai 
コメントありがとうございます。
https://github.com/yumemi-inc/ios-training-bjung/pull/12#discussion_r1470408893
こちらでも書きましたが、warning を解消しようとしていた痕跡です。
自分は削除でいいと思いましたので b8fa170b33fd883fe64067d2a3e3419c148a8db0 で削除しました。

* 意図を持っていたコーディングではなく、修正の痕跡が消されていなかった
* 非 Sendable が入りそうな予定はない
* 自動準拠の知識を得る

2024-02-01 13:55 UTC, novr approved these changes

2024-02-02 00:53 UTC, askldfghj commented
@novr @es-kumagai 
レビューありがとうございます。
こちらマージします。

2024-02-02 01:15 UTC, merged